/**
 * Kâri bilgilerini LibSQL veritabanına aktarır.
 *
 * Kaynak: packages/shared/src/constants/reciters.ts → CURATED_RECITERS
 * Audio URL pattern: QDC (api.qurancdn.com) → chapter recitations endpoint
 */

import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { reciters } from "../src/db/quran-schema";

const client = createClient({
  url: process.env.TURSO_DATABASE_URL || "file:./local.db",
  authToken: process.env.TURSO_AUTH_TOKEN,
});
const db = drizzle(client);

// ── QDC ses URL pattern ────────────────────────────────
// Her kâri için: https://api.qurancdn.com/api/qdc/audio/reciters/{id}/audio_files?chapter={surahId}
// Verse audio: verses.quran.com/{reciterFolder}/{surahPadded}{ayahPadded}.mp3

type VoiceTag = "bas" | "tiz" | "yavas" | "hizli" | "melodik" | "klasik" | "teravih";

type ReciterSeed = {
  slug: string;
  name: string;
  country: string;
  style: string;
  audioBaseUrl: string;
  isDefault: boolean;
  qurancomId: number | null;
  source?: "qurancom" | "self";
  featured?: boolean;
  voiceTags?: VoiceTag[];
};

/**
 * 6 editör tercihi — Kâri Seç ekranının üst kısmında öne çıkar.
 * Tag'ler: bas/tiz vokal aralık, yavas/hizli tempo, melodik/klasik stil, teravih uzun set.
 */
const EDITOR_PICKS: Record<string, { country: string; voiceTags: VoiceTag[] }> = {
  "yasser-ad-dossari":        { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "melodik"] },
  "badr-al-turki":            { country: "Suudi Arabistan", voiceTags: ["tiz", "yavas", "melodik"] },
  "maher-al-muaiqly":         { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "melodik"] },
  "mahmood-ali-al-banna":     { country: "Mısır",           voiceTags: ["tiz", "yavas", "klasik"] },
  "mahmoud-khalil-al-husary": { country: "Mısır",           voiceTags: ["bas", "yavas", "klasik"] },
  "mishary-rashid-alafasy":   { country: "Kuveyt",          voiceTags: ["tiz", "yavas", "melodik"] },
};

/**
 * Yaygın bilinen kâriler için elle doldurulmuş metadata.
 * Slug bilinmiyorsa otomatik olarak boş (Belirtilmemiş) grubuna düşer.
 */
const KNOWN_METADATA: Record<string, { country?: string; voiceTags?: VoiceTag[] }> = {
  "abdur-rahman-as-sudais":        { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "melodik"] },
  "saud-ash-shuraim":              { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "klasik"] },
  "saad-al-ghamdi":                { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "melodik"] },
  "abdulbasit-abdulsamad-murattal":{ country: "Mısır",           voiceTags: ["tiz", "yavas", "klasik"] },
  "abdulbasit-abdulsamad-mujawwad":{ country: "Mısır",           voiceTags: ["tiz", "yavas", "klasik"] },
  "minshawi-murattal":             { country: "Mısır",           voiceTags: ["bas", "yavas", "klasik"] },
  "minshawi-mujawwad":             { country: "Mısır",           voiceTags: ["bas", "yavas", "klasik"] },
  "mahmoud-khalil-al-husary-muallim": { country: "Mısır",        voiceTags: ["bas", "yavas", "klasik"] },
  "khalid-al-jalil":               { country: "Suudi Arabistan", voiceTags: ["tiz", "yavas", "melodik"] },
  "fatih-seferagic":               { country: "Bosna/ABD",       voiceTags: ["tiz", "hizli", "melodik"] },
  "omar-al-qazabri":               { country: "Fas",             voiceTags: ["tiz", "yavas", "melodik"] },
  "abdullah-awad-al-juhani":       { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "melodik"] },
  "abdullah-basfar":               { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "klasik"] },
  "abu-bakr-al-shatri":            { country: "Suudi Arabistan", voiceTags: ["tiz", "yavas", "melodik"] },
  "ali-abdur-rahman-al-huthaify":  { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "klasik"] },
  "abdulmuhsin-al-qasim":          { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "melodik"] },
  "muhammad-jibreel":              { country: "Mısır",           voiceTags: ["tiz", "hizli", "klasik"] },
  "fares-abbad":                   { country: "Suudi Arabistan", voiceTags: ["tiz", "yavas", "melodik"] },
  "salah-bukhatir":                { country: "BAE",             voiceTags: ["bas", "yavas", "klasik"] },
  "salah-al-budair":               { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "klasik"] },
  "hani-ar-rifai":                 { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "melodik"] },
  "ibrahim-al-akhdar":             { country: "Suudi Arabistan", voiceTags: ["tiz", "yavas", "klasik"] },
  "nasser-al-qatami":              { country: "Suudi Arabistan", voiceTags: ["tiz", "yavas", "melodik"] },
  "muhammad-ayyoob":               { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "klasik"] },
  "ahmad-al-huthaify":             { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "klasik"] },
  "abdulbaset-abdulsamad-warsh":   { country: "Mısır",           voiceTags: ["tiz", "yavas", "klasik"] },
  "muhammad-hassan":               { country: "Mısır",           voiceTags: ["bas", "yavas", "klasik"] },
  "mostafa-ismaeel":               { country: "Mısır",           voiceTags: ["tiz", "yavas", "klasik"] },
  "imad-zuhair-hafez":             { country: "Suriye",          voiceTags: ["tiz", "yavas", "melodik"] },
  "adel-kalbani":                  { country: "Suudi Arabistan", voiceTags: ["bas", "yavas", "klasik"] },
  "aziz-alili":                    { country: "Bosna",           voiceTags: ["bas", "yavas", "melodik"] },
};

// Featured kâriler — QDC ID'leri ile
const RECITERS_DATA: readonly ReciterSeed[] = [
  {
    slug: "yasser-ad-dossari",
    name: "Yasser Ad-Dossari",
    country: "Suudi Arabistan",
    style: "murattal",
    audioBaseUrl: "https://verses.quran.com/Yasser_Ad-Dussary_128kbps/mp3",
    isDefault: true,
    qurancomId: 97,
  },
  {
    slug: "mishary-rashid-alafasy",
    name: "Mishari Rashid al-Afasy",
    country: "Kuveyt",
    style: "murattal",
    audioBaseUrl: "https://verses.quran.com/Alafasy/mp3",
    isDefault: false,
    qurancomId: 7,
  },
  {
    slug: "mahmoud-khalil-al-husary",
    name: "Mahmoud Khalil Al-Husary",
    country: "Mısır",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Husary/mp3",
    qurancomId: 6,
  },
  {
    slug: "mahmood-ali-al-banna",
    name: "Mahmood Ali Al-Banna",
    country: "Mısır",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/mahmoud_ali_al_banna/mp3",
    qurancomId: 129,
  },
  {
    slug: "mahmoud-khalil-al-husary-muallim",
    name: "Mahmoud Khalil Al-Husary (Muallim)",
    country: "Mısır",
    style: "muallim",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Husary_Muallim/mp3",
    qurancomId: 12,
  },
  {
    slug: "khalid-al-jalil",
    name: "Khalid Al-Jalil",
    country: "Suudi Arabistan",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/khalid_al_jalil/mp3",
    qurancomId: 170,
  },
  {
    slug: "fatih-seferagic",
    name: "Fatih Seferagic",
    country: "Bosna/ABD",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/fatih_seferagic/mp3",
    qurancomId: 134,
  },
  {
    slug: "abdulbasit-abdulsamad-mujawwad",
    name: "AbdulBaset AbdulSamad",
    country: "Mısır",
    style: "mujawwad",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/AbdulSamad/mp3",
    qurancomId: 1,
  },
  {
    slug: "abdulbasit-abdulsamad-murattal",
    name: "AbdulBaset AbdulSamad",
    country: "Mısır",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Abdul_Basit_Murattal_192kbps/mp3",
    qurancomId: 2,
  },
  {
    slug: "abdur-rahman-as-sudais",
    name: "Abdur-Rahman as-Sudais",
    country: "Suudi Arabistan",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Sudais/mp3",
    qurancomId: 3,
  },
  {
    slug: "maher-al-muaiqly",
    name: "Maher Al-Muaiqly",
    country: "Suudi Arabistan",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/MaherAlMuworthy/mp3",
    qurancomId: 52,
  },
  {
    slug: "saad-al-ghamdi",
    name: "Saad Al-Ghamdi",
    country: "Suudi Arabistan",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Ghamadi_40kbps/mp3",
    qurancomId: 13,
  },
  {
    slug: "saud-ash-shuraim",
    name: "Sa'ud ash-Shuraim",
    country: "Suudi Arabistan",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Shuraym/mp3",
    qurancomId: 10,
  },
  {
    slug: "minshawi-murattal",
    name: "Mohamed Siddiq al-Minshawi",
    country: "Mısır",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Minshawi_Murattal_128kbps/mp3",
    qurancomId: 9,
  },
  {
    slug: "minshawi-mujawwad",
    name: "Mohamed Siddiq al-Minshawi",
    country: "Mısır",
    style: "mujawwad",
    isDefault: false,
    audioBaseUrl: "https://verses.quran.com/Minshawy_Mujawwad_192kbps/mp3",
    qurancomId: 8,
  },
  // ── Chapter-only kâriler (QDC API'de yok — sure-bazlı mp3, ayet senkronu yok) ──
  {
    slug: "badr-al-turki",
    name: "Badr Al-Turki",
    country: "Suudi Arabistan",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/badr_al_turki/mp3",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "omar-al-qazabri",
    name: "Omar Al-Qazabri (Warsh)",
    country: "Fas",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://server9.mp3quran.net/omar_warsh",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdullah-awad-al-juhani",
    name: "Abdullah Awad al-Juhani",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdullaah_3awwaad_al-juhaynee",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdullah-basfar",
    name: "Abdullah Basfar",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdullaah_basfar",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abu-bakr-al-shatri",
    name: "Abu Bakr al-Shatri",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abu_bakr_ash-shaatree",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ali-abdur-rahman-al-huthaify",
    name: "Ali Abdur-Rahman al-Huthaify",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/huthayfi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "khalid-al-qahtani",
    name: "Khalid al-Qahtani",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/khaalid_al-qahtaanee",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "nabil-ar-rifai",
    name: "Nabil ar-Rifai",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/nabil_rifa3i",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulmuhsin-al-qasim",
    name: "AbdulMuhsin al-Qasim",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdul_muhsin_alqasim",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-jibreel",
    name: "Muhammad Jibreel",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/muhammad_jibreel/complete",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "fares-abbad",
    name: "Fares Abbad",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/fares",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulbari-ath-thubaity",
    name: "AbdulBari ath-Thubaity",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/thubaity",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "sahl-yasin",
    name: "Sahl Yasin",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/sahl_yaaseen",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "salah-bukhatir",
    name: "Salah Bukhatir",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/salaah_bukhaatir",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ahmed-ibn-ali-al-ajmy",
    name: "Ahmed ibn Ali al-Ajmy",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/ahmed_ibn_3ali_al-3ajamy",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "sudais-and-shuraym",
    name: "Sudais and Shuraym",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/sodais_and_shuraim",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulazeez-al-ahmad",
    name: "AbdulAzeez al-Ahmad",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulazeez_al-ahmad",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-ayyoob",
    name: "Muhammad Ayyoob",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/muhammad_ayyoob",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "tawfeeq-ibn-said-as-sawaigh",
    name: "Tawfeeq ibn Sa`id as-Sawa'igh",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/tawfeeq_bin_saeed-as-sawaaigh",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdullah-ali-jabir-taraweeh",
    name: "Abdullah Ali Jabir [Taraweeh]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdullaah_alee_jaabir",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-al-mehysni",
    name: "Muhammad al-Mehysni",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mehysni",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "hani-ar-rifai",
    name: "Hani ar-Rifai",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/rifai",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ibrahim-al-jibrin",
    name: "Ibrahim Al-Jibrin",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/jibreen",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulwadud-haneef",
    name: "AbdulWadud Haneef",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulwadood_haneef",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "salah-al-budair",
    name: "Salah al-Budair",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/salahbudair",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "aziz-alili",
    name: "Aziz Alili",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/aziz_alili",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-al-luhaidan",
    name: "Muhammad al-Luhaidan",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/muhammad_alhaidan",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulbaset-abdulsamad-warsh",
    name: "AbdulBaset AbdulSamad [Warsh]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulbaset_warsh",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "al-hussayni-al-azazy-with-children",
    name: "Al-Hussayni Al-'Azazy (with Children)",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/alhusaynee_al3azazee_with_children",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-rashid-sufi-soosi",
    name: "Abdur-Rashid Sufi [Soosi]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdurrashid_sufi_soosi_rec",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "sadaqat-ali",
    name: "Sadaqat `Ali",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/sadaqat_ali",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-rashid-sufi-khalaf",
    name: "Abdur-Rashid Sufi [Khalaf]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdurrashid_sufi_-_khalaf_3an_7amza_recitation",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "hamad-sinan",
    name: "Hamad Sinan",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/hamad_sinan",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-razaq-bin-abtan-al-dulaimi-mujawwad",
    name: "Abdur-Razaq bin Abtan al-Dulaimi [Mujawwad]",
    country: "",
    style: "mujawwad",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulrazaq_bin_abtan_al_dulaimi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdullah-ali-jabir",
    name: "Abdullah Ali Jabir",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdullaah_alee_jaabir_studio",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-abdul-kareem",
    name: "Muhammad Abdul-Kareem",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/muhammad_abdulkareem",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mustafa-al-azawi",
    name: "Mustafa al-`Azawi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mustafa_al3azzawi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdullah-khayat",
    name: "Abdullah Khayat",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/khayat",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mahmoud-khalil-al-husary-doori",
    name: "Mahmoud Khalil Al-Husary [Doori]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mahmood_khaleel_al-husaree_doori",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-hassan",
    name: "Muhammad Hassan",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mu7ammad_7assan",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "salah-al-hashim",
    name: "Salah Al-Hashim",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/salah_alhashim",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "adel-kalbani",
    name: "Adel Kalbani",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/adel_kalbani",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "hatem-farid-taraweeh-1432",
    name: "Hatem Farid - Taraweeh 1432",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/hatem_farid/taraweeh1432",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "hatem-farid-taraweeh-1431",
    name: "Hatem Farid - Taraweeh 1431",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/hatem_farid/taraweeh1431",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mostafa-ismaeel",
    name: "Mostafa Ismaeel",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mostafa_ismaeel",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-sulaiman-patel",
    name: "Muhammad Sulaiman Patel",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/muhammad_patel",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mohammad-al-tablawi",
    name: "Mohammad Al-Tablawi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mohammad_altablawi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mohammad-ismaeel-al-muqaddim",
    name: "Mohammad Ismaeel Al-Muqaddim",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mohammad_ismaeel_almuqaddim",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "imad-zuhair-hafez",
    name: "Imad Zuhair Hafez",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/imad_zuhair_hafez",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mishari-al-afasy-taraweeh-1430",
    name: "Mishari al-`Afasy - Taraweeh 1430",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mishaari_california",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ibrahim-al-akhdar",
    name: "Ibrahim Al Akhdar",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/ibrahim_al_akhdar",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "nasser-al-qatami",
    name: "Nasser Al Qatami",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/nasser_bin_ali_alqatami",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulkareem-al-hazmi",
    name: "AbdulKareem Al Hazmi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulkareem_al_hazmi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-ayyoob-taraweeh",
    name: "Muhammad Ayyoob [Taraweeh]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/muhammad_ayyoob_hq",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdul-munim-abdul-mubdi",
    name: "Abdul-Mun'im Abdul-Mubdi'",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulmun3im_abdulmubdi2",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-rashid-sufi",
    name: "Abdur-Rashid Sufi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdurrashid_sufi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-rashid-sufi-abi-al-haarith-an-al-kasaaee",
    name: "Abdur-Rashid Sufi [Abi al-Haarith an al-Kasaa'ee]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdurrashid_sufi_abi_al7arith",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-rashid-sufi-ad-doori-an-abi-amr",
    name: "Abdur-Rashid Sufi [ad-Doori an Abi Amr]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdurrashid_sufi_doori",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-rashid-sufi-shubah-an-asim",
    name: "Abdur-Rashid Sufi [Shu'bah an Asim]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdurrashid_sufi_shu3ba",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ahmad-al-huthaify",
    name: "Ahmad al-Huthaify",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/ahmad_alhuthayfi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ali-al-huthaify-qaloon",
    name: "Ali al-Huthaify [Qaloon]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/huthayfi_qaloon",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abu-bakr-al-shatri-taraweeh",
    name: "Abu Bakr al-Shatri [Taraweeh]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abu_bakr_ash-shatri_tarawee7",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "idrees-abkar",
    name: "Idrees Abkar",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/idrees_abkar",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "masjid-quba-taraweeh-1434",
    name: "Masjid Quba Taraweeh 1434",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/masjid_quba_1434",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "muhammad-al-mehysni-taraweeh-1435",
    name: "Muhammad al-Mehysni - Taraweeh 1435",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/muhaisny_1435",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdullah-matroud",
    name: "Abdullah Matroud",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdullah_matroud",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulwadood-haneef",
    name: "AbdulWadood Haneef",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdul_wadood_haneef_rare",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ahmad-nauina",
    name: "Ahmad Nauina",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/ahmad_nauina",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "akram-al-alaqmi",
    name: "Akram Al-Alaqmi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/akram_al_alaqmi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "ali-hajjaj-alsouasi",
    name: "Ali Hajjaj Alsouasi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/ali_hajjaj_alsouasi",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mahmood-ali-al-bana",
    name: "Mahmood Ali Al-Bana",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/mahmood_ali_albana",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "wadee-hammadi-al-yamani",
    name: "Wadee Hammadi Al Yamani",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/wadee_hammadi_al-yamani",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "asim-abdul-aleem",
    name: "Asim Abdul Aleem",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/asim_abdulaleem",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdallah-abdal",
    name: "Abdallah Abdal",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdallah_abdal",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdur-rashid-sufi-soosi-2020",
    name: "Abdur-Rashid Sufi [Soosi, 2020]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdurrashid_sufi_soosi_2020",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "hatem-farid-taraweeh-1430",
    name: "Hatem Farid - Taraweeh 1430",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/hatem_farid/taraweeh1430",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mahmoud-khaleel-al-husary-muallam",
    name: "Mahmoud Khaleel Al-Husary (Muallam)",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/husary_muallim",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mahmoud-khaleel-al-husary-with-children",
    name: "Mahmoud Khaleel Al-Husary (with Children)",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/husary_muallim_kids_repeat",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "noreen-siddiq-ad-doori-an-abi-amr",
    name: "Noreen Siddiq [ad-Doori an Abi Amr]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/noreen_siddiq",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "saud-ash-shuraym-older-recitation",
    name: "Sa`ud ash-Shuraym [older recitation]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/sa3ood_al-shuraym/older",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "sudais-and-shuraym-older-recitation",
    name: "Sudais and Shuraym [older recitation]",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/sodais_and_shuraim/older",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "khalifah-taniji",
    name: "Khalifah Taniji",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/khalifah_taniji",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulrahman-al-shahat",
    name: "Abdulrahman al-Shahat",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulrahman_al_shahat",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "abdulaziz-bin-saleh-al-zahrani",
    name: "Abdulaziz bin Saleh al-Zahrani",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/abdulaziz_bin_saleh_alzahrani",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "mahmoud-khaleel-al-husary-mujawwad",
    name: "Mahmoud Khaleel Al-Husary [Mujawwad]",
    country: "",
    style: "mujawwad",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/generated/husary_mujawwad",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "alijon-qari",
    name: "Alijon Qari",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/alijon_qari/mp3",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "raad-mohammad-al-kurdi",
    name: "Raad Mohammad al-Kurdi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/raad_mohammad_al_kurdi/mp3",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "peshawa-qadir-al-kurdi",
    name: "Peshawa Qadir al-Kurdi",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/peshawa_qadir_al-kurdi/mp3",
    qurancomId: null,
    source: "self",
  },
  {
    slug: "farman-shawani",
    name: "Farman Shawani",
    country: "",
    style: "murattal",
    isDefault: false,
    audioBaseUrl: "https://download.quranicaudio.com/quran/farman_shawani/mp3",
    qurancomId: null,
    source: "self",
  },
];

async function main() {
  console.log("Kâriler import ediliyor...\n");

  await db.delete(reciters);

  const rows = RECITERS_DATA.map((r) => {
    const editorPick = EDITOR_PICKS[r.slug];
    const known = KNOWN_METADATA[r.slug];
    const country = editorPick?.country ?? known?.country ?? r.country;
    const voiceTags = editorPick?.voiceTags ?? known?.voiceTags ?? [];
    return {
      slug: r.slug,
      name: r.name,
      country,
      style: r.style,
      audioBaseUrl: r.audioBaseUrl,
      audioFormat: "mp3" as const,
      isDefault: r.isDefault,
      isActive: true,
      source: r.source ?? ("qurancom" as const),
      qurancomId: r.qurancomId,
      featured: !!editorPick,
      voiceTags: JSON.stringify(voiceTags),
    };
  });

  await db.insert(reciters).values(rows);

  console.log(`✓ ${rows.length} kâri eklendi`);
  console.log(`  Varsayılan: ${RECITERS_DATA.find((r) => r.isDefault)?.name}`);

  client.close();
}

main().catch((err) => {
  console.error("HATA:", err);
  process.exit(1);
});
