/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HubRouteImport } from './routes/hub'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as SurahIdRouteImport } from './routes/$surahId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurahSurahSlugRouteImport } from './routes/surah/$surahSlug'
import { Route as PagePageNumberRouteImport } from './routes/page/$pageNumber'
import { Route as JuzJuzIdRouteImport } from './routes/juz/$juzId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as SurahIdVerseNumRouteImport } from './routes/$surahId.$verseNum'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdRoute = SurahIdRouteImport.update({
  id: '/$surahId',
  path: '/$surahId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahSurahSlugRoute = SurahSurahSlugRouteImport.update({
  id: '/surah/$surahSlug',
  path: '/surah/$surahSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageNumberRoute = PagePageNumberRouteImport.update({
  id: '/page/$pageNumber',
  path: '/page/$pageNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const JuzJuzIdRoute = JuzJuzIdRouteImport.update({
  id: '/juz/$juzId',
  path: '/juz/$juzId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdVerseNumRoute = SurahIdVerseNumRouteImport.update({
  id: '/$verseNum',
  path: '/$verseNum',
  getParentRoute: () => SurahIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$surahId': typeof SurahIdRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/hub': typeof HubRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/$surahId/$verseNum': typeof SurahIdVerseNumRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/juz/$juzId': typeof JuzJuzIdRoute
  '/page/$pageNumber': typeof PagePageNumberRoute
  '/surah/$surahSlug': typeof SurahSurahSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$surahId': typeof SurahIdRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/hub': typeof HubRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/$surahId/$verseNum': typeof SurahIdVerseNumRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/juz/$juzId': typeof JuzJuzIdRoute
  '/page/$pageNumber': typeof PagePageNumberRoute
  '/surah/$surahSlug': typeof SurahSurahSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$surahId': typeof SurahIdRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/hub': typeof HubRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/$surahId/$verseNum': typeof SurahIdVerseNumRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/juz/$juzId': typeof JuzJuzIdRoute
  '/page/$pageNumber': typeof PagePageNumberRoute
  '/surah/$surahSlug': typeof SurahSurahSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$surahId'
    | '/bookmarks'
    | '/hub'
    | '/profile'
    | '/search'
    | '/$surahId/$verseNum'
    | '/auth/callback'
    | '/auth/login'
    | '/juz/$juzId'
    | '/page/$pageNumber'
    | '/surah/$surahSlug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$surahId'
    | '/bookmarks'
    | '/hub'
    | '/profile'
    | '/search'
    | '/$surahId/$verseNum'
    | '/auth/callback'
    | '/auth/login'
    | '/juz/$juzId'
    | '/page/$pageNumber'
    | '/surah/$surahSlug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$surahId'
    | '/bookmarks'
    | '/hub'
    | '/profile'
    | '/search'
    | '/$surahId/$verseNum'
    | '/auth/callback'
    | '/auth/login'
    | '/juz/$juzId'
    | '/page/$pageNumber'
    | '/surah/$surahSlug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SurahIdRoute: typeof SurahIdRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  HubRoute: typeof HubRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  JuzJuzIdRoute: typeof JuzJuzIdRoute
  PagePageNumberRoute: typeof PagePageNumberRoute
  SurahSurahSlugRoute: typeof SurahSurahSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$surahId': {
      id: '/$surahId'
      path: '/$surahId'
      fullPath: '/$surahId'
      preLoaderRoute: typeof SurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$surahSlug': {
      id: '/surah/$surahSlug'
      path: '/surah/$surahSlug'
      fullPath: '/surah/$surahSlug'
      preLoaderRoute: typeof SurahSurahSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$pageNumber': {
      id: '/page/$pageNumber'
      path: '/page/$pageNumber'
      fullPath: '/page/$pageNumber'
      preLoaderRoute: typeof PagePageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juz/$juzId': {
      id: '/juz/$juzId'
      path: '/juz/$juzId'
      fullPath: '/juz/$juzId'
      preLoaderRoute: typeof JuzJuzIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$surahId/$verseNum': {
      id: '/$surahId/$verseNum'
      path: '/$verseNum'
      fullPath: '/$surahId/$verseNum'
      preLoaderRoute: typeof SurahIdVerseNumRouteImport
      parentRoute: typeof SurahIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SurahIdRouteChildren {
  SurahIdVerseNumRoute: typeof SurahIdVerseNumRoute
}

const SurahIdRouteChildren: SurahIdRouteChildren = {
  SurahIdVerseNumRoute: SurahIdVerseNumRoute,
}

const SurahIdRouteWithChildren =
  SurahIdRoute._addFileChildren(SurahIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SurahIdRoute: SurahIdRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  HubRoute: HubRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  JuzJuzIdRoute: JuzJuzIdRoute,
  PagePageNumberRoute: PagePageNumberRoute,
  SurahSurahSlugRoute: SurahSurahSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
