/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TajweedRouteImport } from './routes/tajweed'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavunmaRouteImport } from './routes/savunma'
import { Route as ReciteRouteImport } from './routes/recite'
import { Route as QaidaRouteImport } from './routes/qaida'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HifzRouteImport } from './routes/hifz'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HatimIndexRouteImport } from './routes/hatim/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as AlifbaIndexRouteImport } from './routes/alifba/index'
import { Route as SurahSurahSlugRouteImport } from './routes/surah/$surahSlug'
import { Route as PagePageNumberRouteImport } from './routes/page/$pageNumber'
import { Route as JuzJuzIdRouteImport } from './routes/juz/$juzId'
import { Route as HatimGroupIdRouteImport } from './routes/hatim/$groupId'
import { Route as GamesWordMeaningRouteImport } from './routes/games/word-meaning'
import { Route as GamesVerseChainRouteImport } from './routes/games/verse-chain'
import { Route as GamesSurahGuessRouteImport } from './routes/games/surah-guess'
import { Route as GamesHexagonRouteImport } from './routes/games/hexagon'
import { Route as GamesFillBlankRouteImport } from './routes/games/fill-blank'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AnalyseVerseKeyRouteImport } from './routes/analyse/$verseKey'
import { Route as AlifbaGamesRouteImport } from './routes/alifba/games'
import { Route as AlifbaExamRouteImport } from './routes/alifba/exam'
import { Route as AlifbaLetterIdRouteImport } from './routes/alifba/$letterId'
import { Route as AlifbaGamesIndexRouteImport } from './routes/alifba/games/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AlifbaQuizVoiceRouteImport } from './routes/alifba/quiz/voice'
import { Route as AlifbaQuizFormsRouteImport } from './routes/alifba/quiz/forms'
import { Route as AlifbaGamesWordRouteImport } from './routes/alifba/games/word'
import { Route as AlifbaGamesSpeedRouteImport } from './routes/alifba/games/speed'
import { Route as AlifbaGamesMemoryRouteImport } from './routes/alifba/games/memory'
import { Route as AlifbaGamesFillRouteImport } from './routes/alifba/games/fill'

const TajweedRoute = TajweedRouteImport.update({
  id: '/tajweed',
  path: '/tajweed',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavunmaRoute = SavunmaRouteImport.update({
  id: '/savunma',
  path: '/savunma',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciteRoute = ReciteRouteImport.update({
  id: '/recite',
  path: '/recite',
  getParentRoute: () => rootRouteImport,
} as any)
const QaidaRoute = QaidaRouteImport.update({
  id: '/qaida',
  path: '/qaida',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HifzRoute = HifzRouteImport.update({
  id: '/hifz',
  path: '/hifz',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HatimIndexRoute = HatimIndexRouteImport.update({
  id: '/hatim/',
  path: '/hatim/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const AlifbaIndexRoute = AlifbaIndexRouteImport.update({
  id: '/alifba/',
  path: '/alifba/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahSurahSlugRoute = SurahSurahSlugRouteImport.update({
  id: '/surah/$surahSlug',
  path: '/surah/$surahSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageNumberRoute = PagePageNumberRouteImport.update({
  id: '/page/$pageNumber',
  path: '/page/$pageNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const JuzJuzIdRoute = JuzJuzIdRouteImport.update({
  id: '/juz/$juzId',
  path: '/juz/$juzId',
  getParentRoute: () => rootRouteImport,
} as any)
const HatimGroupIdRoute = HatimGroupIdRouteImport.update({
  id: '/hatim/$groupId',
  path: '/hatim/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWordMeaningRoute = GamesWordMeaningRouteImport.update({
  id: '/word-meaning',
  path: '/word-meaning',
  getParentRoute: () => GamesRoute,
} as any)
const GamesVerseChainRoute = GamesVerseChainRouteImport.update({
  id: '/verse-chain',
  path: '/verse-chain',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSurahGuessRoute = GamesSurahGuessRouteImport.update({
  id: '/surah-guess',
  path: '/surah-guess',
  getParentRoute: () => GamesRoute,
} as any)
const GamesHexagonRoute = GamesHexagonRouteImport.update({
  id: '/hexagon',
  path: '/hexagon',
  getParentRoute: () => GamesRoute,
} as any)
const GamesFillBlankRoute = GamesFillBlankRouteImport.update({
  id: '/fill-blank',
  path: '/fill-blank',
  getParentRoute: () => GamesRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseVerseKeyRoute = AnalyseVerseKeyRouteImport.update({
  id: '/analyse/$verseKey',
  path: '/analyse/$verseKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AlifbaGamesRoute = AlifbaGamesRouteImport.update({
  id: '/alifba/games',
  path: '/alifba/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AlifbaExamRoute = AlifbaExamRouteImport.update({
  id: '/alifba/exam',
  path: '/alifba/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AlifbaLetterIdRoute = AlifbaLetterIdRouteImport.update({
  id: '/alifba/$letterId',
  path: '/alifba/$letterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlifbaGamesIndexRoute = AlifbaGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlifbaGamesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AlifbaQuizVoiceRoute = AlifbaQuizVoiceRouteImport.update({
  id: '/alifba/quiz/voice',
  path: '/alifba/quiz/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const AlifbaQuizFormsRoute = AlifbaQuizFormsRouteImport.update({
  id: '/alifba/quiz/forms',
  path: '/alifba/quiz/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AlifbaGamesWordRoute = AlifbaGamesWordRouteImport.update({
  id: '/word',
  path: '/word',
  getParentRoute: () => AlifbaGamesRoute,
} as any)
const AlifbaGamesSpeedRoute = AlifbaGamesSpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => AlifbaGamesRoute,
} as any)
const AlifbaGamesMemoryRoute = AlifbaGamesMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AlifbaGamesRoute,
} as any)
const AlifbaGamesFillRoute = AlifbaGamesFillRouteImport.update({
  id: '/fill',
  path: '/fill',
  getParentRoute: () => AlifbaGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/changelog': typeof ChangelogRoute
  '/discover': typeof DiscoverRoute
  '/games': typeof GamesRouteWithChildren
  '/hifz': typeof HifzRoute
  '/notes': typeof NotesRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/qaida': typeof QaidaRoute
  '/recite': typeof ReciteRoute
  '/savunma': typeof SavunmaRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/tajweed': typeof TajweedRoute
  '/alifba/$letterId': typeof AlifbaLetterIdRoute
  '/alifba/exam': typeof AlifbaExamRoute
  '/alifba/games': typeof AlifbaGamesRouteWithChildren
  '/analyse/$verseKey': typeof AnalyseVerseKeyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/games/fill-blank': typeof GamesFillBlankRoute
  '/games/hexagon': typeof GamesHexagonRoute
  '/games/surah-guess': typeof GamesSurahGuessRoute
  '/games/verse-chain': typeof GamesVerseChainRoute
  '/games/word-meaning': typeof GamesWordMeaningRoute
  '/hatim/$groupId': typeof HatimGroupIdRoute
  '/juz/$juzId': typeof JuzJuzIdRoute
  '/page/$pageNumber': typeof PagePageNumberRoute
  '/surah/$surahSlug': typeof SurahSurahSlugRoute
  '/alifba/': typeof AlifbaIndexRoute
  '/games/': typeof GamesIndexRoute
  '/hatim/': typeof HatimIndexRoute
  '/alifba/games/fill': typeof AlifbaGamesFillRoute
  '/alifba/games/memory': typeof AlifbaGamesMemoryRoute
  '/alifba/games/speed': typeof AlifbaGamesSpeedRoute
  '/alifba/games/word': typeof AlifbaGamesWordRoute
  '/alifba/quiz/forms': typeof AlifbaQuizFormsRoute
  '/alifba/quiz/voice': typeof AlifbaQuizVoiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/alifba/games/': typeof AlifbaGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/changelog': typeof ChangelogRoute
  '/discover': typeof DiscoverRoute
  '/hifz': typeof HifzRoute
  '/notes': typeof NotesRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/qaida': typeof QaidaRoute
  '/recite': typeof ReciteRoute
  '/savunma': typeof SavunmaRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/tajweed': typeof TajweedRoute
  '/alifba/$letterId': typeof AlifbaLetterIdRoute
  '/alifba/exam': typeof AlifbaExamRoute
  '/analyse/$verseKey': typeof AnalyseVerseKeyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/games/fill-blank': typeof GamesFillBlankRoute
  '/games/hexagon': typeof GamesHexagonRoute
  '/games/surah-guess': typeof GamesSurahGuessRoute
  '/games/verse-chain': typeof GamesVerseChainRoute
  '/games/word-meaning': typeof GamesWordMeaningRoute
  '/hatim/$groupId': typeof HatimGroupIdRoute
  '/juz/$juzId': typeof JuzJuzIdRoute
  '/page/$pageNumber': typeof PagePageNumberRoute
  '/surah/$surahSlug': typeof SurahSurahSlugRoute
  '/alifba': typeof AlifbaIndexRoute
  '/games': typeof GamesIndexRoute
  '/hatim': typeof HatimIndexRoute
  '/alifba/games/fill': typeof AlifbaGamesFillRoute
  '/alifba/games/memory': typeof AlifbaGamesMemoryRoute
  '/alifba/games/speed': typeof AlifbaGamesSpeedRoute
  '/alifba/games/word': typeof AlifbaGamesWordRoute
  '/alifba/quiz/forms': typeof AlifbaQuizFormsRoute
  '/alifba/quiz/voice': typeof AlifbaQuizVoiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/alifba/games': typeof AlifbaGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/changelog': typeof ChangelogRoute
  '/discover': typeof DiscoverRoute
  '/games': typeof GamesRouteWithChildren
  '/hifz': typeof HifzRoute
  '/notes': typeof NotesRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/qaida': typeof QaidaRoute
  '/recite': typeof ReciteRoute
  '/savunma': typeof SavunmaRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/tajweed': typeof TajweedRoute
  '/alifba/$letterId': typeof AlifbaLetterIdRoute
  '/alifba/exam': typeof AlifbaExamRoute
  '/alifba/games': typeof AlifbaGamesRouteWithChildren
  '/analyse/$verseKey': typeof AnalyseVerseKeyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/games/fill-blank': typeof GamesFillBlankRoute
  '/games/hexagon': typeof GamesHexagonRoute
  '/games/surah-guess': typeof GamesSurahGuessRoute
  '/games/verse-chain': typeof GamesVerseChainRoute
  '/games/word-meaning': typeof GamesWordMeaningRoute
  '/hatim/$groupId': typeof HatimGroupIdRoute
  '/juz/$juzId': typeof JuzJuzIdRoute
  '/page/$pageNumber': typeof PagePageNumberRoute
  '/surah/$surahSlug': typeof SurahSurahSlugRoute
  '/alifba/': typeof AlifbaIndexRoute
  '/games/': typeof GamesIndexRoute
  '/hatim/': typeof HatimIndexRoute
  '/alifba/games/fill': typeof AlifbaGamesFillRoute
  '/alifba/games/memory': typeof AlifbaGamesMemoryRoute
  '/alifba/games/speed': typeof AlifbaGamesSpeedRoute
  '/alifba/games/word': typeof AlifbaGamesWordRoute
  '/alifba/quiz/forms': typeof AlifbaQuizFormsRoute
  '/alifba/quiz/voice': typeof AlifbaQuizVoiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/alifba/games/': typeof AlifbaGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/changelog'
    | '/discover'
    | '/games'
    | '/hifz'
    | '/notes'
    | '/premium'
    | '/profile'
    | '/qaida'
    | '/recite'
    | '/savunma'
    | '/search'
    | '/stats'
    | '/tajweed'
    | '/alifba/$letterId'
    | '/alifba/exam'
    | '/alifba/games'
    | '/analyse/$verseKey'
    | '/auth/callback'
    | '/auth/login'
    | '/games/fill-blank'
    | '/games/hexagon'
    | '/games/surah-guess'
    | '/games/verse-chain'
    | '/games/word-meaning'
    | '/hatim/$groupId'
    | '/juz/$juzId'
    | '/page/$pageNumber'
    | '/surah/$surahSlug'
    | '/alifba/'
    | '/games/'
    | '/hatim/'
    | '/alifba/games/fill'
    | '/alifba/games/memory'
    | '/alifba/games/speed'
    | '/alifba/games/word'
    | '/alifba/quiz/forms'
    | '/alifba/quiz/voice'
    | '/api/auth/$'
    | '/alifba/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/changelog'
    | '/discover'
    | '/hifz'
    | '/notes'
    | '/premium'
    | '/profile'
    | '/qaida'
    | '/recite'
    | '/savunma'
    | '/search'
    | '/stats'
    | '/tajweed'
    | '/alifba/$letterId'
    | '/alifba/exam'
    | '/analyse/$verseKey'
    | '/auth/callback'
    | '/auth/login'
    | '/games/fill-blank'
    | '/games/hexagon'
    | '/games/surah-guess'
    | '/games/verse-chain'
    | '/games/word-meaning'
    | '/hatim/$groupId'
    | '/juz/$juzId'
    | '/page/$pageNumber'
    | '/surah/$surahSlug'
    | '/alifba'
    | '/games'
    | '/hatim'
    | '/alifba/games/fill'
    | '/alifba/games/memory'
    | '/alifba/games/speed'
    | '/alifba/games/word'
    | '/alifba/quiz/forms'
    | '/alifba/quiz/voice'
    | '/api/auth/$'
    | '/alifba/games'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/changelog'
    | '/discover'
    | '/games'
    | '/hifz'
    | '/notes'
    | '/premium'
    | '/profile'
    | '/qaida'
    | '/recite'
    | '/savunma'
    | '/search'
    | '/stats'
    | '/tajweed'
    | '/alifba/$letterId'
    | '/alifba/exam'
    | '/alifba/games'
    | '/analyse/$verseKey'
    | '/auth/callback'
    | '/auth/login'
    | '/games/fill-blank'
    | '/games/hexagon'
    | '/games/surah-guess'
    | '/games/verse-chain'
    | '/games/word-meaning'
    | '/hatim/$groupId'
    | '/juz/$juzId'
    | '/page/$pageNumber'
    | '/surah/$surahSlug'
    | '/alifba/'
    | '/games/'
    | '/hatim/'
    | '/alifba/games/fill'
    | '/alifba/games/memory'
    | '/alifba/games/speed'
    | '/alifba/games/word'
    | '/alifba/quiz/forms'
    | '/alifba/quiz/voice'
    | '/api/auth/$'
    | '/alifba/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  ChangelogRoute: typeof ChangelogRoute
  DiscoverRoute: typeof DiscoverRoute
  GamesRoute: typeof GamesRouteWithChildren
  HifzRoute: typeof HifzRoute
  NotesRoute: typeof NotesRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  QaidaRoute: typeof QaidaRoute
  ReciteRoute: typeof ReciteRoute
  SavunmaRoute: typeof SavunmaRoute
  SearchRoute: typeof SearchRoute
  StatsRoute: typeof StatsRoute
  TajweedRoute: typeof TajweedRoute
  AlifbaLetterIdRoute: typeof AlifbaLetterIdRoute
  AlifbaExamRoute: typeof AlifbaExamRoute
  AlifbaGamesRoute: typeof AlifbaGamesRouteWithChildren
  AnalyseVerseKeyRoute: typeof AnalyseVerseKeyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  HatimGroupIdRoute: typeof HatimGroupIdRoute
  JuzJuzIdRoute: typeof JuzJuzIdRoute
  PagePageNumberRoute: typeof PagePageNumberRoute
  SurahSurahSlugRoute: typeof SurahSurahSlugRoute
  AlifbaIndexRoute: typeof AlifbaIndexRoute
  HatimIndexRoute: typeof HatimIndexRoute
  AlifbaQuizFormsRoute: typeof AlifbaQuizFormsRoute
  AlifbaQuizVoiceRoute: typeof AlifbaQuizVoiceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tajweed': {
      id: '/tajweed'
      path: '/tajweed'
      fullPath: '/tajweed'
      preLoaderRoute: typeof TajweedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savunma': {
      id: '/savunma'
      path: '/savunma'
      fullPath: '/savunma'
      preLoaderRoute: typeof SavunmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recite': {
      id: '/recite'
      path: '/recite'
      fullPath: '/recite'
      preLoaderRoute: typeof ReciteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qaida': {
      id: '/qaida'
      path: '/qaida'
      fullPath: '/qaida'
      preLoaderRoute: typeof QaidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hifz': {
      id: '/hifz'
      path: '/hifz'
      fullPath: '/hifz'
      preLoaderRoute: typeof HifzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatim/': {
      id: '/hatim/'
      path: '/hatim'
      fullPath: '/hatim/'
      preLoaderRoute: typeof HatimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/alifba/': {
      id: '/alifba/'
      path: '/alifba'
      fullPath: '/alifba/'
      preLoaderRoute: typeof AlifbaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$surahSlug': {
      id: '/surah/$surahSlug'
      path: '/surah/$surahSlug'
      fullPath: '/surah/$surahSlug'
      preLoaderRoute: typeof SurahSurahSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$pageNumber': {
      id: '/page/$pageNumber'
      path: '/page/$pageNumber'
      fullPath: '/page/$pageNumber'
      preLoaderRoute: typeof PagePageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juz/$juzId': {
      id: '/juz/$juzId'
      path: '/juz/$juzId'
      fullPath: '/juz/$juzId'
      preLoaderRoute: typeof JuzJuzIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatim/$groupId': {
      id: '/hatim/$groupId'
      path: '/hatim/$groupId'
      fullPath: '/hatim/$groupId'
      preLoaderRoute: typeof HatimGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/word-meaning': {
      id: '/games/word-meaning'
      path: '/word-meaning'
      fullPath: '/games/word-meaning'
      preLoaderRoute: typeof GamesWordMeaningRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/verse-chain': {
      id: '/games/verse-chain'
      path: '/verse-chain'
      fullPath: '/games/verse-chain'
      preLoaderRoute: typeof GamesVerseChainRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/surah-guess': {
      id: '/games/surah-guess'
      path: '/surah-guess'
      fullPath: '/games/surah-guess'
      preLoaderRoute: typeof GamesSurahGuessRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/hexagon': {
      id: '/games/hexagon'
      path: '/hexagon'
      fullPath: '/games/hexagon'
      preLoaderRoute: typeof GamesHexagonRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/fill-blank': {
      id: '/games/fill-blank'
      path: '/fill-blank'
      fullPath: '/games/fill-blank'
      preLoaderRoute: typeof GamesFillBlankRouteImport
      parentRoute: typeof GamesRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/$verseKey': {
      id: '/analyse/$verseKey'
      path: '/analyse/$verseKey'
      fullPath: '/analyse/$verseKey'
      preLoaderRoute: typeof AnalyseVerseKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alifba/games': {
      id: '/alifba/games'
      path: '/alifba/games'
      fullPath: '/alifba/games'
      preLoaderRoute: typeof AlifbaGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alifba/exam': {
      id: '/alifba/exam'
      path: '/alifba/exam'
      fullPath: '/alifba/exam'
      preLoaderRoute: typeof AlifbaExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alifba/$letterId': {
      id: '/alifba/$letterId'
      path: '/alifba/$letterId'
      fullPath: '/alifba/$letterId'
      preLoaderRoute: typeof AlifbaLetterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alifba/games/': {
      id: '/alifba/games/'
      path: '/'
      fullPath: '/alifba/games/'
      preLoaderRoute: typeof AlifbaGamesIndexRouteImport
      parentRoute: typeof AlifbaGamesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alifba/quiz/voice': {
      id: '/alifba/quiz/voice'
      path: '/alifba/quiz/voice'
      fullPath: '/alifba/quiz/voice'
      preLoaderRoute: typeof AlifbaQuizVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alifba/quiz/forms': {
      id: '/alifba/quiz/forms'
      path: '/alifba/quiz/forms'
      fullPath: '/alifba/quiz/forms'
      preLoaderRoute: typeof AlifbaQuizFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alifba/games/word': {
      id: '/alifba/games/word'
      path: '/word'
      fullPath: '/alifba/games/word'
      preLoaderRoute: typeof AlifbaGamesWordRouteImport
      parentRoute: typeof AlifbaGamesRoute
    }
    '/alifba/games/speed': {
      id: '/alifba/games/speed'
      path: '/speed'
      fullPath: '/alifba/games/speed'
      preLoaderRoute: typeof AlifbaGamesSpeedRouteImport
      parentRoute: typeof AlifbaGamesRoute
    }
    '/alifba/games/memory': {
      id: '/alifba/games/memory'
      path: '/memory'
      fullPath: '/alifba/games/memory'
      preLoaderRoute: typeof AlifbaGamesMemoryRouteImport
      parentRoute: typeof AlifbaGamesRoute
    }
    '/alifba/games/fill': {
      id: '/alifba/games/fill'
      path: '/fill'
      fullPath: '/alifba/games/fill'
      preLoaderRoute: typeof AlifbaGamesFillRouteImport
      parentRoute: typeof AlifbaGamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesFillBlankRoute: typeof GamesFillBlankRoute
  GamesHexagonRoute: typeof GamesHexagonRoute
  GamesSurahGuessRoute: typeof GamesSurahGuessRoute
  GamesVerseChainRoute: typeof GamesVerseChainRoute
  GamesWordMeaningRoute: typeof GamesWordMeaningRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesFillBlankRoute: GamesFillBlankRoute,
  GamesHexagonRoute: GamesHexagonRoute,
  GamesSurahGuessRoute: GamesSurahGuessRoute,
  GamesVerseChainRoute: GamesVerseChainRoute,
  GamesWordMeaningRoute: GamesWordMeaningRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface AlifbaGamesRouteChildren {
  AlifbaGamesFillRoute: typeof AlifbaGamesFillRoute
  AlifbaGamesMemoryRoute: typeof AlifbaGamesMemoryRoute
  AlifbaGamesSpeedRoute: typeof AlifbaGamesSpeedRoute
  AlifbaGamesWordRoute: typeof AlifbaGamesWordRoute
  AlifbaGamesIndexRoute: typeof AlifbaGamesIndexRoute
}

const AlifbaGamesRouteChildren: AlifbaGamesRouteChildren = {
  AlifbaGamesFillRoute: AlifbaGamesFillRoute,
  AlifbaGamesMemoryRoute: AlifbaGamesMemoryRoute,
  AlifbaGamesSpeedRoute: AlifbaGamesSpeedRoute,
  AlifbaGamesWordRoute: AlifbaGamesWordRoute,
  AlifbaGamesIndexRoute: AlifbaGamesIndexRoute,
}

const AlifbaGamesRouteWithChildren = AlifbaGamesRoute._addFileChildren(
  AlifbaGamesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  ChangelogRoute: ChangelogRoute,
  DiscoverRoute: DiscoverRoute,
  GamesRoute: GamesRouteWithChildren,
  HifzRoute: HifzRoute,
  NotesRoute: NotesRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  QaidaRoute: QaidaRoute,
  ReciteRoute: ReciteRoute,
  SavunmaRoute: SavunmaRoute,
  SearchRoute: SearchRoute,
  StatsRoute: StatsRoute,
  TajweedRoute: TajweedRoute,
  AlifbaLetterIdRoute: AlifbaLetterIdRoute,
  AlifbaExamRoute: AlifbaExamRoute,
  AlifbaGamesRoute: AlifbaGamesRouteWithChildren,
  AnalyseVerseKeyRoute: AnalyseVerseKeyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  HatimGroupIdRoute: HatimGroupIdRoute,
  JuzJuzIdRoute: JuzJuzIdRoute,
  PagePageNumberRoute: PagePageNumberRoute,
  SurahSurahSlugRoute: SurahSurahSlugRoute,
  AlifbaIndexRoute: AlifbaIndexRoute,
  HatimIndexRoute: HatimIndexRoute,
  AlifbaQuizFormsRoute: AlifbaQuizFormsRoute,
  AlifbaQuizVoiceRoute: AlifbaQuizVoiceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
