/**
 * Loader for the static Quran word pool generated by
 * `scripts/generate-word-pool.ts`. Pool is split into two buckets:
 *   normal — frequently-occurring words (easier to recognize)
 *   zor    — rare or grammatically inflected forms
 */

import { useQuery } from "@tanstack/react-query";

export interface QuranWord {
  arabic: string;
  meaning: string;
}

interface PoolPayload {
  generatedAt: string;
  counts: { normal: number; zor: number; total: number };
  normal: QuranWord[];
  zor: QuranWord[];
}

export type WordPoolBucket = "normal" | "zor";

async function fetchPool(): Promise<PoolPayload> {
  const r = await fetch("/data/quran-word-pool.json");
  if (!r.ok) throw new Error("Failed to load word pool");
  return r.json();
}

export function useQuranWordPool() {
  return useQuery({
    queryKey: ["quran-word-pool"],
    queryFn: fetchPool,
    staleTime: Infinity,
  });
}

/** Map game-scoring difficulty to a word-pool bucket. */
export function bucketForDifficulty(d: "easy" | "medium" | "hard" | "hafiz"): WordPoolBucket {
  return d === "easy" || d === "medium" ? "normal" : "zor";
}
