/**
 * Sure tanıtım metinleri -- her surenin kısa özeti.
 * Surah header altında, bismillah üstünde gösterilir.
 */

const TR: Record<number, string> = {
  1: "Kur'an-ı Kerim'in ilk suresi. Namazın her rekatında okunan, 'Açılış' anlamına gelen yedi ayetlik bu sure, kulun Rabbiyle konuşmasının özüdür.",
  2: "Kur'an'ın en uzun suresi. İman, ibadet, hukuk ve toplum hayatına dair kapsamlı hükümler içerir. Adını içindeki inek kıssasından alır.",
  3: "Hz. İmran'ın ailesini, Hz. Meryem'i ve Hz. İsa'yı anlatır. Uhud Savaşı'na dair dersler ve sabırla ilgili öğütler içerir.",
  4: "Kadın hakları, yetimler, miras hukuku ve aile düzeniyle ilgili temel hükümler sunar. Toplumsal adaleti vurgular.",
  5: "Ahde vefa, helal-haram ölçüleri ve Hz. İsa ile havarilerin sofra kıssasını anlatır.",
  6: "Tevhid inancını güçlendiren deliller sunar. Putperestliğe karşı aklı ve naklı kanıtlar ortaya koyar.",
  7: "İnsanlık tarihinden kıssalar aktarır. Adem'den başlayarak peygamberlerin kavimlerine tebliğini anlatır.",
  8: "Bedir Savaşı ve ganimetlerin paylaşımını konu alır. Savaşın ilahi yardımla kazanıldığını hatırlatır.",
  9: "Münafıklarla ve ahdi bozanlarla ilişkileri düzenler. Kur'an'da besmeleyle başlamayan tek suredir.",
  10: "Hz. Yunus'un kıssası üzerinden sabırla tebliği ve tevbenin önemini işler.",
  11: "Hz. Nuh, Hud, Salih, İbrahim, Lut ve Şuayb kıssalarını anlatır. Peygamberlerin azim ve sebatını vurgular.",
  12: "Hz. Yusuf'un hayatını baştan sona aktaran tek sure. Sabır, iffet ve affın en güzel örneklerini sunar.",
  13: "Göklerdeki ve yerdeki ilahi işaret ve delilleri gösterir. Ra'd (gök gürültüsü) Allah'ı tesbih eder.",
  14: "Hz. İbrahim'in duaları ve nimete şükür ile nankörlüğün sonuçlarını işler.",
  15: "Hicr bölgesinde helak edilen Semud kavminin kıssasını ve Kur'an'ın korunacağı vaadini içerir.",
  16: "Bal arısı örneğiyle Allah'ın yarattığı nimetleri sıralar. Şükür ve nankörlüğün sonuçlarını anlatır.",
  17: "Hz. Peygamber'in Mescid-i Haram'dan Mescid-i Aksa'ya gece yolculuğunu anlatır. Ahlaki ilkeler ortaya koyar.",
  18: "Ashab-ı Kehf, Hz. Musa-Hızır ve Zülkarneyn kıssalarını içerir. Cuma günleri okunması tavsiye edilir.",
  19: "Hz. Meryem ve Hz. İsa'nın doğumunu, Hz. İbrahim, Musa, Harun ve İdris'i anlatır.",
  20: "Hz. Musa'nın peygamber oluşu ve Firavun'la mücadelesini detaylı biçimde anlatır.",
  21: "Birçok peygamberin kıssalarını özet olarak aktarır. Peygamberlerin ortak mesajını vurgular.",
  22: "Hac ibadeti, kurban ve tevhid inancını işler. İnsanın yaratılışındaki ilahi hikmete dikkat çeker.",
  23: "Müminlerin temel özelliklerini sıralar. Kıyamet ve hesap günü sahneleri sunar.",
  24: "İffet, mahremiyet ve toplumsal ahlak kuralları koyar. Nur ayeti ile ilahi hidayeti sembolize eder.",
  25: "Kur'an'ın hak ile batılı ayıran ölçü (furkan) olduğunu vurgular. Rahmani kulların özelliklerini sıralar.",
  26: "Musa, İbrahim, Nuh, Hud, Salih, Lut ve Şuayb kıssalarını aktarır. Şuaraların etkisine değinir.",
  27: "Hz. Süleyman'ın karınca ve Belkıs kıssasını anlatır. İlahi kudret ve hikmet örnekleri sunar.",
  28: "Hz. Musa'nın çocukluğu, Medyen'e gidişi ve peygamber oluşu ayrıntılı anlatılır.",
  29: "İmtihan ve sınavların hikmeti üzerinde durur. Örümcek ağı metaforuyla sahte dayanakları anlatır.",
  30: "Bizans-Sasani savaşına işaret eden gaybi mucizeyi içerir. Yaratılıştaki ilahi işaretleri sıralar.",
  31: "Lokman'ın oğluna verdiği hikmetli öğütleri aktarır. Ana babaya iyilik ve tevhid vurgulanır.",
  32: "Yaratılış, ölüm ve yeniden diriliş gerçeğini hatırlatır. Gece ibadetinin faziletine değinir.",
  33: "Hendek Savaşı, peygamber hanımları ve hicab ayetlerini içerir. Toplumsal düzen kuralları koyar.",
  34: "Sebe kavminin kıssası ve nimetlere nankörlük. Hz. Davud ve Süleyman'ın nimetlere şükrü anlatılır.",
  35: "Allah'ın yaratma kudretini ve nimetlerini anlatan deliller sunar. Fatır, yoktan var eden demektir.",
  36: "Kur'an'ın kalbi olarak bilinen sure. Ölü bir beldenin diriltilmesi örneği üzerinden ahireti ispatlar.",
  37: "Meleklerin saf saf dizilişini ve ahiret sahnelerini tasvir eder. Hz. İbrahim'in kurban kıssasını içerir.",
  38: "Hz. Davud, Süleyman ve Eyyub kıssaları üzerinden sabır, şükür ve hikmet derslerini verir.",
  39: "İhlaslı kulluk, tevbe ve Allah'ın rahmetine sığınma çağrısı yapar. Kıyamet sahnelerini canlı şekilde tasvir eder.",
  40: "Firavun sarayında iman eden bir kişinin cesaretini anlatır. Dua ve tebliğin önemini vurgular.",
  41: "Kur'an ayetlerinin açıklanan, ayrıntılı kılındığı vurgulanır. İnananlara müjde, inkar edenlere uyarı içerir.",
  42: "Sure, istişare (danışma) ilkesini öne çıkarır. Toplumsal kararlarda ortak akla başvurmayı öğütler.",
  43: "Altın süsler üzerinden dünya hayatının aldatıcılığı anlatılır. Tevhid inancının delilleri sunulur.",
  44: "Kıyametteki duman (duhan) hadisesini ve Firavun'un helakını konu alır.",
  45: "İnkar edenlerin 'dizüstü çökecegi' kıyamet sahnesini tasvir eder. Yaratılıştaki ilahi delilleri sıralar.",
  46: "Kum tepeleri bölgesindeki Ad kavminin helakını anlatır. Ana babaya iyiliği emreder.",
  47: "Savaş hükümleri ve münafığın durumunu işler. Sure, Hz. Muhammed'in (s.a.v.) adını taşır.",
  48: "Hudeybiye Barış Antlaşması'nın 'açık bir fetih' olduğunu müjdeler. Rıdvan biati anlatılır.",
  49: "Toplumsal adab ve görgüleri öğretir. Zan, gıybet ve alaydan sakınmayı emreder.",
  50: "Yeniden diriliş gerçeği üzerine deliller sunar. İnsana şah damarından yakın olan Allah'ı hatırlatır.",
  51: "Rüzgarlar üzerinden ilahi kudrete dikkat çekilir. Hz. İbrahim'e gelen meleklerin kıssasını içerir.",
  52: "Tur dağı üzerine yemin ederek ahiret gerçeğini vurgular. Cennet ve cehennem tasvirlerini içerir.",
  53: "Hz. Peygamber'in Mirac yolculuğundaki ilahi yakınlığı anlatır. Yıldız üzerine yemin içerir.",
  54: "Ayın yarılması mucizesi ve geçmiş kavimlerin helakı üzerinden ibreti işler.",
  55: "'Allah'ın hangi nimetlerini yalanlayabilirsiniz?' nakaratı ile ilahi nimetleri sıralar.",
  56: "Kıyamet kopacağı gün insanların üç sınıfa ayrılacağını anlatır: Öncüler, ashab-ı yemin ve ashab-ı şimal.",
  57: "Demirin önemi, dünya hayatının faniliği ve infakın fazileti işlenir. Allah'ın zikrine çağrı yapar.",
  58: "Kocasından Allah'a şikayette bulunan kadının kıssasını anlatır. Gizli konuşma adabını öğretir.",
  59: "Beni Nadir Yahudilerinin sürülmesi ve fey (ganimet) hükümlerini içerir. Haşir gününü hatırlatır.",
  60: "Müşrik kadınlarla evlilik hükümleri ve düşmana karşı dengeli tutum konusunda yol gösterir.",
  61: "Allah yolunda saf tutup mücadele etmenin önemi ve Hz. İsa'nın Hz. Muhammed'i müjdelemesi anlatılır.",
  62: "Cuma namazı emri ve ticareti bırakıp namaza koşma çağrısı içerir.",
  63: "Münafıkların iç yüzlerini, ikiyüzlülüklerini ve topluma verdikleri zararı anlatır.",
  64: "Dünya malına aldanmamanın ve karşılıklı aldanmanın (tegabun) gününün uyarısı yapılır.",
  65: "Boşanma hükümlerini ve iddet sürelerini düzenler. Takvanın önemini vurgular.",
  66: "Hz. Peygamber'in eş ilişkilerindeki bir hadiseye değinir. İffetli kadınları örnek gösterir.",
  67: "Ölüm ve hayatın imtihan için yaratıldığını vurgular. Göklerdeki ilahi sanat ve kudrete dikkat çeker.",
  68: "Kalem ve yazının önemi üzerinden başlar. Ahlaki ilkeleri ve sabrı öğütler.",
  69: "Kıyametin kopuşunu canlı sahnelerle tasvir eder. Ad ve Semud kavimlerinin helakını hatırlatır.",
  70: "Azabın gerçekliğini ve kıyametin kaçınılmazlığını vurgular. Müminlerin özelliklerini sıralar.",
  71: "Hz. Nuh'un uzun soluklu tebliğini ve kavminin inadını anlatır. Nuh'un duasını içerir.",
  72: "Cinlerin Kur'an'ı dinleyip iman etmesini anlatır. Gayb bilgisinin yalnız Allah'a ait olduğunu vurgular.",
  73: "Gece ibadetinin önemini ve Kur'an'ı ağır ağır okumayı (tertil) emreder.",
  74: "Tebliğ görevinin başlamasını emreder. Cehennem bekçisi meleklerden ve büyük günahlardan söz eder.",
  75: "Kıyameti ve yeniden dirilişi inkara karşı deliller sunar. İnsanın kemiklerinin bile toplanacağını bildirir.",
  76: "İnsanın yaratılış serüveni ve cennetteki nimetlerin ayrıntılı tasvirini sunar.",
  77: "Art arda gönderilen rüzgarlar ve kıyamet manzaraları üzerinden ahireti hatırlatır.",
  78: "Kıyamet ve yeniden diriliş haberleri hakkındaki büyük tartışmayı konu alır.",
  79: "Ruh çekenleri ve kıyametin dehşetini tasvir eder. Hz. Musa-Firavun kıssasına değinir.",
  80: "Hz. Peygamber'in ama bir sahabiye karşı tutumunu düzeltir. İnsanın nankörlüğünün eleştirisini yapar.",
  81: "Kıyametin kopuşundaki kozmik değişiklikleri tasvir eder. Güneşin dürülmesi ile başlar.",
  82: "Göğün yarılması ve amel defterlerinin açılması sahnelerini anlatır.",
  83: "Ölçüde ve tartıda hile yapanları uyarır. İlliyyin ve siccin defterlerinden bahseder.",
  84: "Göğün yarılıp Rabbine itaat etmesi sahnesini anlatır. Amel defterlerinin dağıtımını tasvir eder.",
  85: "Ashab-ı Uhdud (hendek/ateş kazısı) kıssasını anlatır. İman edenlere yapılan zulmü lanetler.",
  86: "Gece yıldızı (tarık) üzerine yemin eder. İnsanın yaratılışındaki ilahi kudreti hatırlatır.",
  87: "Yüce Allah'ın isim ve sıfatlarını tesbih eder. İlk sahifelerdeki ortak mesajı hatırlatır.",
  88: "Kıyamet gününü 'her şeyi saracak olay' olarak tasvir eder. Cennet ve cehennem tabloları çizer.",
  89: "Fecir vaktine yemin ederek Ad, Semud ve Firavun'un helakını hatırlatır. Nefsin temizlenmesini öğütler.",
  90: "Mekke şehri üzerine yemin ederek hayatın zorluklarını ve iyilik yolunu anlatır.",
  91: "Güneş üzerine yemin ederek nefis tezkiyesinin önemini vurgular. Semud kavminin helakını hatırlatır.",
  92: "Gece ve gündüz üzerine yemin ederek cömertlik ve cimrilik arasındaki farkı ortaya koyar.",
  93: "Hz. Peygamber'e teselli veren sure. Allah'ın lütuflarını hatırlatır ve yetim ile yoksula iyiliği emreder.",
  94: "Hz. Peygamber'in göğsünün açılmasını ve her zorluğun ardından bir kolaylık geldiğini müjdeler.",
  95: "İncir ve zeytin üzerine yemin ederek insanın en güzel biçimde yaratıldığını bildirir.",
  96: "İlk inen ayetleri içerir. 'Oku!' emriyle başlar. İlim, kalem ve insanın yaratılışını konu alır.",
  97: "Kadir Gecesi'nin bin aydan hayırlı olduğunu müjdeler. Meleklerin o gece indiğini haber verir.",
  98: "Açık delilin gelmesiyle Ehl-i Kitab ve müşriklerin tutumlarını anlatır.",
  99: "Yerin şiddetli sarsıntısını ve insanların amellerinin ortaya döküleceğini tasvir eder.",
  100: "Savaşın hızını ve insanın nankörlüğünün sertliğini coşan atlar metaforuyla anlatır.",
  101: "Kıyametin büyük vurucu olayı ve amellerin tartılmasını tasvir eder.",
  102: "Dünya hırsıyla oyalananın ahireti unutmasını uyarır. Kabirlere kadar süren yarışma eleştirilir.",
  103: "Üç ayetiyle insanlığın kurtuluşunun özeti. İman, salih amel, hak ve sabır tavsiyesi.",
  104: "Arkasından çekiştiren, mal yığıp sayan kimseleri uyarır. Hutame ateşini anlatır.",
  105: "Fil ordosuyla Kabe'yi yıkma girişiminin ilahi müdahaleyle engellenmesini anlatır.",
  106: "Kureyş kabilesinin yaz ve kış ticaret yolculuklarını ve Allah'a şükrü emreder.",
  107: "Din gününü yalanlayanların özelliklerini sıralar. Yetime ve yoksula ilgisizliği eleştirir.",
  108: "Kevser nimetinin Hz. Peygamber'e verildiğini müjdeler. Kurbana ve namaza yönlendirir.",
  109: "Müslümanların inanç özgürlüğünü ilan eder. 'Sizin dininiz size, benim dinim bana' ilkesini koyar.",
  110: "Mekke'nin fethini ve insanların bölük bölük İslam'a girişini müjdeler. Son inen surelerdendir.",
  111: "Ebu Leheb ve karısının Hz. Peygamber'e düşmanlıklarını ve akıbetlerini bildirir.",
  112: "Tevhidin en öz ifadesi. Allah'ın birliğini, samedliğini ve eşsizliğini dört ayette özetler.",
  113: "Karanlık, büyü ve haset gibi dış kötülüklerden Allah'a sığınmayı öğretir.",
  114: "İnsanın içine vesvese veren şeytandan Allah'a sığınmayı öğretir. Kur'an'ın son suresidir.",
};

/** Returns the surah description for the given locale. */
export function getSurahDescription(surahId: number, _locale: string = "tr"): string | undefined {
  return TR[surahId];
}
